### PR TITLE
Refresh when node changed. Fix background seed

### LINKED ISSUE #38: Refresh bar code if new version of parity is detected
Currently it's cached indefinitely

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes #38

### CODE REVIEW

File: background/state.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export default {
+  version: null
```
Comment (ngotchac) [inline background/state.js:2]: It seems to work, but wouldn't it be future-proof/extensible to have something like

```javascript
class State {
  version = null;
}

const state = new State();

export default state;
```

**Review by ngotchac — APPROVED** [review]

File: background/state.js (hunk 1 above)
Comment (derhuerst) [reply background/state.js:2]: In which way would that be more or less extensible?

Comment (ngotchac) [reply background/state.js:2]: `State` sounds very general ; we might want to add some methods to it, I don't know... It was more a question than a comment though

Comment (derhuerst) [reply background/state.js:2]: I'd rather separate state-mutating things from the state itself. I'm not sure the `State` we're talking about here is intended the "state" we usually refer to.

Comment (tomusdrw) [reply background/state.js:2]: Would be good to introduce some redux-like state object anyway, for couple of stuff or re-implement the whole background script initialization to be in a single place instead of loading bunch of modules that attach some listeners on their own.

Comment (ngotchac) [reply background/state.js:2]: Right. We could use MobX with singletons I guess, might be lighter
