### PR TITLE
Fix getDappsAddresses

### LINKED ISSUE #62: Exponential backoff when refreshing accounts seems broken
I run my PR which renamed `parity_getDappsAddresses` to `parity_getDappAddresses` and extension was generating ~300req/s to fetch dapp accounts.

- [ ] Exponentation backoff should work
- [ ] Different methods should be used dependening on version.

### PR DESCRIPTION
**Pull request by tomusdrw**
Fixes #62 
Turns out the error was caused by invalid use of `sendMessage`:

> In the above example, sendResponse was called synchronously. If you want to asynchronously use sendResponse, add return true; to the onMessage event handler.

https://developer.chrome.com/extensions/messaging

### CODE REVIEW

File: background/transport.js [hunk 1]
```diff
@@ -261,6 +261,11 @@ export default class Transport {
 
   fetchAccountsForCache (origin) {
     return this.transport.execute('parity_getDappsAddresses', origin)
+      .then(null, () => {
```
Comment (ngotchac) [inline background/transport.js]: Is it equivalent to a `catch` ?

**Review by ngotchac — APPROVED** [review]
Looks good !

File: background/transport.js (hunk 1 above)
Comment (tomusdrw) [reply background/transport.js]: Yes, I thought that `catch` doesn't return promise, so you can only use it at the very end, but it seems that that those two are equivalent, will update this.

Comment (derhuerst) [reply background/transport.js]: `Promise` behaves like a monoid, every method (`then`, `catch` and `finally` in the future) returns a new Promise that resolves or rejects just like `new Promise(() => …)` does.

From my memory, not sure: `catch` catches every previous rejection, whereas `b` in `.then(a, b)` does not handle rejections of `a`.

In this specific case, using `catch(f)` should be more idiomatic than `then(null, f)`.
